Table dbo.association_names {
  lid PK
  name nvarchar(max)
}

Table dbo.associations {
  lid PK
  employee_lid int
  related_to nvarchar(max)
  related_to_lid int
  association_fklid int
}

Table dbo.bu_rsu_starting_points {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_startingpoints nvarchar(max)
  str_country nvarchar(510)
  b_disabled bit
  str_zip nvarchar(510)
  str_city nvarchar(510)
}

Table dbo.business_areas {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_business_area nvarchar(510)
}

Table dbo.carerepdata {
  lid PK
  luserid int
  luseridinsert int
  dtinsert datetime2
  dtedit datetime2
  str_titel_6a585d30 nvarchar(510)
  l_bu int
  str_bu nvarchar(510)
  dt_date datetime2
  str_kicgperson nvarchar(510)
  b_casestudycontribution bit
  b_growthrevenuevstarget bit
  l_numberofconsultants int
  str_growthcomment nvarchar(510)
  str_commentonhr nvarchar(510)
  b_timelysalesdashboardusage bit
  b_plannerusage bit
  str_commentplannerusage nvarchar(510)
  str_commentcasestudy nvarchar(510)
  str_commentsalesdashboard nvarchar(510)
  str_bestpracticestosharewithot nvarchar(510)
  str_networkcollaborationcommun nvarchar(510)
  b_kikprocessimplementedandfoll bit
  str_commentonkikprocess nvarchar(510)
  b_aaeabmparticipation bit
  str_commentonaaeabmparticipati nvarchar(510)
  txt_generalmotivationlevelandk nvarchar(max)
}

Table dbo.casestudies_core {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_coretechnology nvarchar(510)
}

Table dbo.casestudies_db {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  ref_40b92bee int
  ref_a3b038b4 int
  txt_introductiondescription nvarchar(max)
  txt_docurrentstatewhyisitaprob nvarchar(max)
  txt_check nvarchar(max)
  txt_act nvarchar(max)
  str_permission nvarchar(510)
  str_subtitleforthiscasestudy nvarchar(510)
  ref_45cf59ee int
  str_projectcode nvarchar(510)
  l_file int
  bdlcguid nvarchar(510)
  str_file nvarchar(max)
  b_checked_by_kiag bit
}

Table dbo.casestudies_mainsectors {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_mainsector nvarchar(510)
}

Table dbo.casestudies_product {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_productpackaging nvarchar(510)
}

Table dbo.changes_log {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_before nvarchar(max)
  str_after nvarchar(max)
  str_table nvarchar(510)
  id int
  str_operation nvarchar(510)
  dt_effective_change datetime2
  b_hide bit
}

Table dbo.co2_emission_general_types {
  lid PK
  str_label nvarchar(510)
}

Table dbo.co2_emission_reasons {
  lid PK
  str_label nvarchar(510)
}

Table dbo.co2_emission_specific_types {
  lid PK
  str_label nvarchar(510)
}

Table dbo.co2_emissions_factors_per_country {
  lid PK
  str_country nvarchar(500)
  str_emission_category nvarchar(500)
  str_emission_detail nvarchar(500)
  flt_emission_factor float
  str_emission_source nvarchar(500)
}

Table dbo.co2_expenses_metadata {
  lid PK
  flt_distance float
  str_type_of_train nvarchar(100)
  fklid int
  txt_ai_json nvarchar(max)
  str_transportation_mode nvarchar(100)
  txt_route nvarchar(max)
  str_ai_model nvarchar(100)
  str_batch_name nvarchar(500)
  flt_amount float
  txt_ai_explanation nvarchar(max)
  str_start_time nvarchar(510)
  str_end_time nvarchar(510)
  flt_diff_route_time float
  txt_distance_json nvarchar(max)
  ref_co2_single_emission bigint
}

Table dbo.co2_general_type_unity_map {
  lid PK
  general_type_id int
  unity_id int
}

Table dbo.co2_generaltype_specific_map {
  lid PK
  general_type_id int
  specific_type_id int
}

Table dbo.co2_po_invoices_metadata {
  lid PK
  flt_distance float
  str_type_of_train nvarchar(100)
  fklid int
  txt_ai_json nvarchar(max)
  str_transportation_mode nvarchar(100)
  txt_route nvarchar(max)
  str_ai_model nvarchar(100)
  str_batch_name nvarchar(500)
  flt_amount float
  txt_ai_explanation nvarchar(max)
  str_start_time nvarchar(510)
  str_end_time nvarchar(510)
  flt_diff_route_time float
  txt_distance_json nvarchar(max)
  ref_co2_single_emission bigint
}

Table dbo.co2_reason_general_map {
  lid PK
  reason_id int
  general_id int
}

Table dbo.co2_single_emissions {
  lid PK
  luserid bigint
  luseridinsert bigint
  dtinsert datetime
  dtedit datetime
  str_emission_reason nvarchar(510)
  str_general_type nvarchar(200)
  str_specific_type nvarchar(200)
  lamount decimal(18,2)
  lamount_offset decimal(18,2)
  lkgCO2 float
  lyear int
  lmonth int
  str_country nvarchar(100)
  str_metric_co2 varchar(255)
  ref_expense int
  str_project_code nvarchar(100)
  str_consultant nvarchar(510)
}

Table dbo.co2_unities {
  lid PK
  str_unity nvarchar(510)
}

Table dbo.consultants_hourly_rate {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_consultant nvarchar(510)
  flt_hourly_rate float
  b_consider_for_unreported bit
}

Table dbo.countries_iso {
  lid PK
  str_code nvarchar(100)
  str_country nvarchar(510)
  str_currency nvarchar(100)
}

Table dbo.cvs_academics {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_licenciatura_faculdade nvarchar(510)
  str_licenciatura_curso nvarchar(510)
  b_licenciatura_frequentar bit
  flt_licenciatura_media float
  str_mestrado_faculdade nvarchar(510)
  str_mestrado_curso nvarchar(510)
  b_mestrado_frequentar bit
  flt_mestrado_media float
  str_mestrado_integrado_faculdade nvarchar(510)
  str_mestrado_integrado_curso nvarchar(510)
  b_mestrado_integrado_frequentar bit
  flt_mestrado_integrado_media float
  l_ano_licenciatura int
  l_ano_mestrado int
  l_ano_mestrado_integrado int
  l_anolicenciaturainicio int
  str_douturamentocurso nvarchar(510)
  str_douturamentofaculdade nvarchar(510)
  flt_douturamentomedia float
  l_anodouturamentofim int
  l_anodouturamentoinicio int
  l_anomestradoinicio int
  l_anomestradointegradoinicio int
  str_outrosfaculdade nvarchar(510)
  str_outroscurso nvarchar(510)
  flt_outrosmedia float
  l_anooutrosinicio int
  l_anooutrosfim int
}

Table dbo.cvs_languages {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_languages nvarchar(510)
  b_native bit
  b_advanced bit
  b_medium bit
  b_basic bit
  str_level nvarchar(510)
}

Table dbo.cvs_personal_data {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name nvarchar(510)
  dt_birthdate datetime2
  str_email nvarchar(510)
  str_city nvarchar(510)
  str_phone nvarchar(510)
  str_photo nvarchar(510)
  b_erasmus bit
  str_erasmuscity nvarchar(510)
  str_erasmuscountry nvarchar(510)
  str_erasmusfaculty nvarchar(510)
  txt_experiences nvarchar(max)
  str_cvfile nvarchar(510)
  b_contacted bit
  str_status nvarchar(510)
  str_country nvarchar(510)
  b_exported bit
  txt_cvknowledgekaizen nvarchar(max)
  str_cvsapplicationdata nvarchar(510)
  str_cvreference nvarchar(510)
}

Table dbo.cvs_professional_experience {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  dt_from datetime2
  dt_to datetime2
  str_company nvarchar(510)
  txt_description nvarchar(max)
}

Table dbo.day_lid_matrix_rate_table {
  day_lid int
  matrix_lid int
  flt_rate float
  rate_currency nvarchar(510)
}

Table dbo.dsobject {
  lid PK
  lcontainerid int
  strname nvarchar(508)
  lclassid int
  strguid nvarchar(80)
  lpriority int
  bdeletable bit
  bdeleted bit
  bdisabled bit
  linternalusn int
  strrplguid nvarchar(80)
  strdn nvarchar(1024)
  strdescription nvarchar(1024)
  strexternalguid nvarchar(80)
}

Table dbo.dsuser {
  lid PK
  lboss int
  strlogin nvarchar(508)
  strdomain nvarchar(96)
  strloginlwr nvarchar(508)
  strdomainlwr nvarchar(96)
  dtpwdchanged datetime2
  strpwdhash nvarchar(80)
  strsalt nvarchar(20)
  bpwdexpires bit
  bmustchangepass bit
  bmustnotchangepass bit
  bshowuser bit
  strfullname nvarchar(344)
  strfirstname nvarchar(128)
  strmiddlename nvarchar(128)
  strlastname nvarchar(128)
  strtitle nvarchar(128)
  stremployeeno nvarchar(32)
  dtenter datetime2
  lgender int
  dtbirth datetime2
  strstreet nvarchar(192)
  strpostalcode nvarchar(20)
  strpobox nvarchar(20)
  strcity nvarchar(192)
  strstate nvarchar(64)
  strcountry nvarchar(64)
  strphonebiz nvarchar(80)
  strphonemobilebiz nvarchar(80)
  strphonehome nvarchar(80)
  strphonemobilehome nvarchar(80)
  strphonefax nvarchar(80)
  strphonepager nvarchar(80)
  strmailbiz nvarchar(508)
  strmailhome nvarchar(508)
  strtimezone nvarchar(64)
  lextprimgrpid int
  strextlogin1 nvarchar(80)
  strextpwd1 nvarchar(80)
  strextlogin2 nvarchar(80)
  strextpwd2 nvarchar(80)
  strextlogin3 nvarchar(80)
  strextpwd3 nvarchar(80)
  strdefaultlayout nvarchar(160)
  lproxyperson int
  strimg_contenttype nvarchar(100)
  strimg_filename nvarchar(510)
  strimg_url nvarchar(510)
  strdefaultlang nvarchar(4)
  dtimg_lastmodified datetime2
  strimg_meta nvarchar(4096)
  countrylong nvarchar(64)
  curr nvarchar(6)
  strdefaultlocale nvarchar(100)
  lloginattempts int
  bislockable bit
  llocked int
}

Table dbo.dsuser_ad {
  lid int
  lboss int
  strlogin nvarchar(96)
  strdomain nvarchar(96)
  strloginlwr nvarchar(96)
  strdomainlwr nvarchar(96)
  dtpwdchanged datetime2
  strpwdhash nvarchar(80)
  strsalt nvarchar(20)
  bpwdexpires bit
  bmustchangepass bit
  bmustnotchangepass bit
  bshowuser bit
  strfullname nvarchar(296)
  strfirstname nvarchar(96)
  strmiddlename nvarchar(96)
  strlastname nvarchar(96)
  strtitle nvarchar(96)
  stremployeeno nvarchar(32)
  dtenter datetime2
  lgender int
  dtbirth datetime2
  strstreet nvarchar(192)
  strpostalcode nvarchar(20)
  strpobox nvarchar(20)
  strcity nvarchar(192)
  strstate nvarchar(64)
  strcountry nvarchar(64)
  strphonebiz nvarchar(80)
  strphonemobilebiz nvarchar(80)
  strphonehome nvarchar(80)
  strphonemobilehome nvarchar(80)
  strphonefax nvarchar(80)
  strphonepager nvarchar(80)
  strmailbiz nvarchar(384)
  strmailhome nvarchar(384)
  strtimezone nvarchar(64)
  lextprimgrpid int
  strextlogin1 nvarchar(80)
  strextpwd1 nvarchar(80)
  strextlogin2 nvarchar(80)
  strextpwd2 nvarchar(80)
  strextlogin3 nvarchar(80)
  strextpwd3 nvarchar(80)
  strdefaultlayout nvarchar(160)
  lproxyperson int
  strimg_contenttype nvarchar(100)
  strimg_filename nvarchar(510)
  strimg_url nvarchar(510)
  strdefaultlang nvarchar(4)
  strname nvarchar(256)
  strguid nvarchar(80)
  bdeleted bit
  bdisabled bit
  strdescription nvarchar(510)
  countrylong nvarchar(64)
  curr nvarchar(6)
}

Table dbo.employee_member_type {
  lid PK
  fklid int
  l_id int
}

Table dbo.employees_with_connected_countries_mat {
  lid int
  employee_country nvarchar(510)
  rsu_country nvarchar(510)
  connected_country nvarchar(510)
  strcountry nvarchar(510)
  employee_full_country varchar(255)
  employee_currency nvarchar(510)
  ki_company_name nvarchar(510)
  country_lid int
  company_id int
}

Table dbo.event_payment_status {
  lid int
  fklid int
  paid bit
  dtinsert datetime2
}

Table dbo.excluded_days {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_day_id int
  str_country nvarchar(510)
  ref_e21519c4 int
}

Table dbo.expense_log_not_changed_tracker {
  lid PK
  expense_id int
  change_log_lid int
}

Table dbo.expenses_log_track {
  lid PK
  expense_id int
  operation nvarchar(500)
  who nvarchar(500)
  field nvarchar(500)
  from nvarchar(max)
  to nvarchar(max)
  when datetime2
  change_log_lid bigint
}

Table dbo.expenses_reject_reasons_rel {
  lid PK
  standard_lid int
  specific_lid int
}

Table dbo.expenses_reject_reasons_specific {
  lid PK
  str_specific_reason nvarchar(2000)
  str_standard_reason nvarchar(400)
}

Table dbo.expenses_reject_reasons_standard {
  lid PK
  str_standard_reason nvarchar(400)
}

Table dbo.expenses_reviewers {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_reviewer nvarchar(510)
  str_countries nvarchar(510)
  str_project nvarchar(510)
}

Table dbo.extracted_tolls {
  lid PK
  str_starting_zip nvarchar(510)
  str_starting_city nvarchar(510)
  str_starting_country nvarchar(510)
  str_destination_zip nvarchar(510)
  str_destination_city nvarchar(510)
  str_destination_country nvarchar(510)
  fklid int
  dtinsert datetime2
  dtedit datetime2
  str_duration nvarchar(100)
  str_total_kms nvarchar(100)
  str_total_toll nvarchar(100)
}

Table dbo.factorial_employees_teams_clean_mat {
  username nvarchar(max)
  teams nvarchar(max)
}

Table dbo.fast_username_lid_mat {
  username nvarchar(510)
  strcountry nvarchar(510)
  lid int
  is_disabled bit
  first_name nvarchar(510)
  last_name nvarchar(510)
  full_name nvarchar(1022)
  username_full_name nvarchar(510)
  employee_full_country varchar(255)
  employee_lid int
  position nvarchar(510)
  employee_currency nvarchar(510)
  str_kms_currency nvarchar(100)
  is_business_owner_member bit
  is_credit_card_member bit
  is_nonrefundable bit
  travel_perk_id int
  position_title nvarchar(510)
  ki_zip_code nvarchar(510)
  ref_startingpointlid int
  b_is_qatar_id bit
  ki_city nvarchar(510)
}

Table dbo.helpdesk_activity {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_json nvarchar(max)
  fklid int
  str_message_id nvarchar(max)
}

Table dbo.helpdesk_scopes {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_scope nvarchar(510)
  str_description nvarchar(max)
}

Table dbo.helpdesk_sub_category {
  lid PK
  dtinsert datetime2
  dtedit datetime2
  luserid int
  luseridinsert int
  str_sub_category nvarchar(510)
  fklid int
}

Table dbo.helpdesk_ticket {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_scope nvarchar(510)
  str_sub_category nvarchar(510)
  str_assigned_to nvarchar(510)
  str_description nvarchar(max)
  str_file nvarchar(max)
  str_critical_level nvarchar(510)
  str_status nvarchar(510)
  str_email_sent_by nvarchar(510)
  str_message_id nvarchar(max)
  str_subject nvarchar(510)
  str_body_preview nvarchar(max)
  str_admin_comment nvarchar(max)
  flt_total_working_hour float
  b_handled_by_expert bit
  txt_expert_was_needed nvarchar(max)
  b_not_it_issue bit
  str_it_comment varchar(255)
}

Table dbo.hubspot_contact_embeddings {
  lid PK
  txt_embeddings nvarchar(max)
  txt_txt nvarchar(max)
  hubspot_contact_id nvarchar(510)
  dt_insert datetime2
  dt_edit datetime2
  txt_json nvarchar(max)
}

Table dbo.hubspot_contacts_missing_qualification {
  lid PK
  dt_edit datetime2
  dt_insert datetime2
  str_linkedin_url nvarchar(510)
  txt_json nvarchar(max)
  str_job_role nvarchar(510)
  str_department nvarchar(510)
  str_industry nvarchar(510)
  str_macro_sector nvarchar(510)
  str_company_employees nvarchar(510)
  str_hubspot_id nvarchar(510)
  str_job_title nvarchar(510)
  str_first_name nvarchar(510)
  str_last_name nvarchar(510)
  str_company_name nvarchar(510)
  str_connected_company_id nvarchar(510)
  dt_last_time_linkedin_parsed datetime2
  str_email nvarchar(510)
  str_location nvarchar(510)
  str_company_url nvarchar(510)
  str_specialties nvarchar(max)
  txt_proxy_curl nvarchar(max)
  str_occupation_present nvarchar(max)
  str_headline nvarchar(max)
  txt_open_ai_response nvarchar(max)
  txt_context_used nvarchar(max)
  txt_open_ai_json nvarchar(max)
  b_synced bit
  txt_notes nvarchar(max)
  txt_proxy_company nvarchar(max)
  b_company_synced bit
  txt_company_notes nvarchar(max)
  str_step nvarchar(510)
  str_company_domain nvarchar(510)
  str_open_ai_company_country nvarchar(510)
  b_is_refresh bit
}

Table dbo.hubspot_kim_sync {
  lid PK
  hubspot_object_type nvarchar(100)
  hubspot_object_id nvarchar(100)
  kim_table nvarchar(100)
  kim_lid int
  dtinsert datetime2
  dtedit datetime2
  connected_to_correct_company nvarchar(100)
}

Table dbo.hubspot_merge_group_companies {
  lid PK
  fklid int
  str_hubspot_company_id nvarchar(510)
  dtinsert datetime2
  str_company_name nvarchar(510)
  b_marked_hubspot bit
}

Table dbo.hubspot_merge_groups {
  lid PK
  str_domain nvarchar(200)
  str_hq_hubspot_company_id nvarchar(510)
  dtinsert datetime2
  str_hq_name nvarchar(510)
  b_dismissed bit
  b_marked_hubspot bit
}

Table dbo.ideas_collection {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  str_category nvarchar(510)
  txt_description nvarchar(max)
  str_implementation nvarchar(510)
  str_subject nvarchar(510)
  b_active bit
  txt_current_state nvarchar(max)
  l_fileinformation int
  str_status nvarchar(510)
  txt_response nvarchar(max)
  bdlcguid nvarchar(510)
  str_implementationteam nvarchar(510)
  str_datafield nvarchar(510)
  str_projectmanager nvarchar(510)
  str_responsible nvarchar(510)
  l_requestedby int
  txt_file_url nvarchar(max)
  str_sub_category nvarchar(max)
  l_up_votes int
  l_required_upvotes int
  str_priority nvarchar(510)
  str_department nvarchar(510)
  dt_due_date datetime
  copied bit
  int_process_impact int
  int_end_customer_impact int
  int_organizational_reach int
  int_financial_impact int
  int_time_sensitivity int
  int_root_cause_clarity int
  int_solution_complexity int
  int_dependencies int
  str_link nvarchar(510)
  str_owner nvarchar(510)
}

Table dbo.invoice_payments {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  payment_date datetime2
  amount float
  fklid int
  unique_id nvarchar(max)
  last_sync datetime2
  str_quickbooks_id nvarchar(510)
  str_payment_info nvarchar(510)
  str_payment_comment varchar(max)
}

Table dbo.invoices_connections {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_original int
  l_copy int
}

Table dbo.kaizen_event_workshops {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name nvarchar(510)
  b_disabled bit
  b_is_new bit
}

Table dbo.ki_employee_team {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_team nvarchar(510)
  str_country nvarchar(510)
  str_group_id nvarchar(max)
  str_owners nvarchar(max)
}

Table dbo.ki_suggestion_box_sub_categories {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_sub_category nvarchar(max)
  b_disabled bit
}

Table dbo.ki_surveys {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  str_country nvarchar(510)
  str_name nvarchar(510)
  ref_c99f2e19 int
  str_title nvarchar(510)
  str_recipientemail nvarchar(510)
  txt_flowendpoint nvarchar(max)
  str_thanks nvarchar(max)
  str_submit nvarchar(510)
  str_language nvarchar(510)
  is_project_connected bit
}

Table dbo.kim_settings {
  lid PK
  settings nvarchar(max)
  dtinsert datetime2
  dtedit datetime2
  luserid int
  luseridinsert int
}

Table dbo.kim_team_members {
  lid PK
  fklid int
  lemployee_lid int
  dtedit datetime2
  dtinsert datetime2
  str_member_level nvarchar(100)
  dt_valid_from datetime2
  dt_valid_to datetime2
  b_ki_member_entry bit
}

Table dbo.kim_team_members_history_metadata {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  fklid bigint
  b_hide bit
  dt_effective_change datetime2
  lemployee_lid int
  was_on_team int
  went_to_team int
  team_change_date datetime2
}

Table dbo.kim_teams {
  lid PK
  dtinsert datetime2
  dtedit datetime2
  str_team nvarchar(510)
  str_group_id nvarchar(300)
  str_country_scope nvarchar(100)
  b_is_ki_member_team bit
  b_is_dynamic bit
  b_email_list bit
  txt_filters nvarchar(max)
  luserid int
  luseridinsert int
  str_email_list_name nvarchar(510)
  b_create_microsoft_team bit
}

Table dbo.member_types {
  lid PK
  str_member_type nvarchar(510)
}

Table dbo.new_kim_employees {
  lid PK
  str_first_name nvarchar(510)
  str_last_name nvarchar(510)
  str_country nvarchar(510)
  dt_birthday datetime2
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  fklid int
  str_supervisor nvarchar(510)
}

Table dbo.office_licenses {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_license_name nvarchar(max)
  str_description nvarchar(max)
  flt_cost float
  str_skus nvarchar(max)
  b_essential bit
}

Table dbo.outlook_sync_registrations {
  lid PK
  username nvarchar(510)
  str_mode nvarchar(100)
}

Table dbo.parent_rate_matrix {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  flt_after_invoiced_amount float
  dt_start_date datetime2
  dt_end_date datetime2
  str_name nvarchar(510)
  txt_connectedprojects nvarchar(max)
  str_currency nvarchar(510)
}

Table dbo.payment_conditions {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_country nvarchar(510)
  str_payment_condition nvarchar(510)
  str_postfix_code nvarchar(510)
  str_old_payment_condition nvarchar(510)
}

Table dbo.planner_configlink {
  lid PK
  dtinsert datetime2
  luseridinsert int
  dtedit datetime2
  luserid int
  flt_amount float
  l_year int
  ref_7d7d69f5 int
  ref_385db616 int
  str_country_c95409fc nvarchar(510)
  str_month_8903eacd nvarchar(510)
}

Table dbo.planner_reviewers {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_reviewer nvarchar(510)
  str_countries nvarchar(510)
  str_project nvarchar(510)
}

Table dbo.po_invoices {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_purchase_order nvarchar(100)
  str_invoice_number nvarchar(510)
  str_description nvarchar(max)
  dec_amount decimal(18,2)
  str_currency nvarchar(20)
  dt_invoice_date datetime2
  dt_due_date datetime2
  str_status nvarchar(200)
  txt_image_url nvarchar(max)
  str_doc_type varchar(255)
  str_vat_number varchar(255)
  str_supplier varchar(255)
  str_article_code varchar(255)
  flt_tax_percentage float
  str_project_code varchar(255)
  str_consultant varchar(255)
  str_notes varchar(max)
  dt_start_date date
  dt_end_date date
  str_ai_status nvarchar(100)
  str_supplier_country varchar(10)
  str_supplier_country_source varchar(20)
  str_source_file_name nvarchar(510)
  co2_relevant nvarchar(2)
}

Table dbo.po_items {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_item varchar(255)
  str_category varchar(255)
  bool_needs_approval bit
}

Table dbo.project_business_areas {
  lid PK
  fklid int
  l_id int
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
}

Table dbo.project_consultant_cicles {
  lid PK
  consultant nvarchar(510)
  cicle int
  cicle_value float
  cicle_ref int
  cicle_start_date date
  project_code nvarchar(510)
  is_manual_value bit
}

Table dbo.project_consultant_delivery_ratio {
  lid PK
  project_code nvarchar(510)
  consultant nvarchar(510)
  rate float
}

Table dbo.project_invoicing_project {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  fklid int
  l_id int
}

Table dbo.projects_country_deliver_days {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_country nvarchar(510)
  flt_days float
}

Table dbo.projects_invoice_filter {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_country nvarchar(510)
  str_projectcode nvarchar(510)
  str_filter nvarchar(510)
}

Table dbo.projects_starting_points_km {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_country nvarchar(510)
  ref_startingpoints int
  flt_km_per_project float
  flt_toll_amount float
  flt_km_per_project_trainee float
}

Table dbo.projects_workshops {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name nvarchar(510)
  str_kpi_type nvarchar(510)
  flt_present_value float
  flt_starting_value float
  flt_goal float
  flt_total_days float
  str_status nvarchar(510)
  l_planned_actions int
  l_finished_actions int
  txt_workshop_objectives nvarchar(max)
  str_responsible_consultant nvarchar(510)
  ref_ceb9881a int
}

Table dbo.rates_matrix {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name nvarchar(510)
  str_project_code nvarchar(510)
  dt_from datetime2
  dt_to datetime2
  str_consultant nvarchar(510)
  str_role nvarchar(510)
  str_activity nvarchar(510)
  str_country nvarchar(510)
  flt_rate float
  str_currency nvarchar(510)
  flt_invoiced_volume float
  flt_rate_deduction float
  str_deduction_type nvarchar(510)
  ref_9dd190f6 int
  b_hourly_rate bit
  flt_invoicedrate float
  str_invoiced_currency nvarchar(510)
  txt_connectedprojects nvarchar(max)
  ref_8961cb0a int
  str_unreported_country nvarchar(510)
}

Table dbo.receipts_emails_expenses {
  lid PK
  ref_expense int
  ref_receipts_debug bigint
}

Table dbo.routes_distances {
  lid PK
  str_starting_zip nvarchar(100)
  str_starting_city nvarchar(510)
  str_starting_country nvarchar(510)
  str_destination_zip nvarchar(100)
  str_destination_city nvarchar(510)
  str_duration nvarchar(100)
  flt_kms float
  dtinsert datetime2
  dtedit datetime2
  b_from_google bit
  str_destination_country nvarchar(510)
  b_distance_pair_is_valid bit
  flt_tolls float
  b_toll_is_valid bit
  flt_distance_in_miles float
}

Table dbo.soft_skills {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name nvarchar(510)
  flt_score float
  str_type nvarchar(510)
}

Table dbo.starting_point_tolls_details {
  lid PK
  str_starting_zip nvarchar(510)
  str_starting_city nvarchar(510)
  str_starting_country nvarchar(510)
  str_destination_zip nvarchar(510)
  str_destination_street_city nvarchar(510)
  str_destination_country nvarchar(510)
  str_duration nvarchar(510)
  str_total_kms nvarchar(510)
  str_total_toll nvarchar(510)
  int_total_routs int
  int_route_number int
  str_scrapped_starting_point nvarchar(max)
  str_scrapped_destination_point nvarchar(max)
  dtinsert datetime2
  outside_eu bit
  dtedit datetime2
  luserid int
  luseridinsert int
  b_from_google bit
  b_distance_pair_is_valid bit
  b_calculate_tolls bit
}

Table dbo.starting_point_tolls_details_test {
  lid int
  str_starting_zip nvarchar(510)
  str_starting_city nvarchar(510)
  str_starting_country nvarchar(510)
  str_destination_zip nvarchar(510)
  str_destination_street_city nvarchar(510)
  str_destination_country nvarchar(510)
  str_duration nvarchar(510)
  str_total_kms nvarchar(510)
  str_total_toll nvarchar(510)
  int_total_routs int
  int_route_number int
  str_scrapped_starting_point nvarchar(max)
  str_scrapped_destination_point nvarchar(max)
  dtinsert datetime2
  outside_eu bit
  dtedit datetime2
  luserid int
  luseridinsert int
}

Table dbo.surveys_tracking {
  lid PK
  fklid int
  str_status nvarchar(510)
  connected_day int
  txt_notes nvarchar(max)
  dtinsert datetime2
  dtedit datetime2
  is_project bit
  helpdesk_ticket int
}

Table dbo.table_log {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_table nvarchar(510)
  l_entrylid int
  str_operation nvarchar(510)
  txt_changes nvarchar(max)
}

Table dbo.travelperkcostcenter {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  fklid int
  travelperk_id int
  travelperk_costcenter varchar(50)
  travelperk_archived bit
  travelperk_users nvarchar(max)
  travelperk_count_users int
  b_in_sync bit
}

Table dbo.user_sites_permissions {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_url nvarchar(max)
  str_username nvarchar(510)
  b_has_access bit
}

Table dbo.users_licenses {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
  fklid int
  str_country nvarchar(510)
  str_email nvarchar(510)
  str_mode nvarchar(510)
  dt_expiration_date datetime2
  b_request_removal bit
  l_project_lid int
}

Table dbo.utils_table {
  lid PK
  str_name nvarchar(510)
  str_json nvarchar(max)
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
}

Table dbo.validated_routes {
  lid PK
  postal_code nvarchar(500)
  city nvarchar(500)
  b_processed bit
}

Table dbo.vbluser_mat {
  lid int
  lboss int
  strlogin nvarchar(508)
  strdomain nvarchar(96)
  strloginlwr nvarchar(508)
  strdomainlwr nvarchar(96)
  dtpwdchanged datetime2
  strpwdhash nvarchar(80)
  strsalt nvarchar(20)
  bpwdexpires bit
  bmustchangepass bit
  bmustnotchangepass bit
  lloginattempts int
  bislockable bit
  llocked int
  bshowuser bit
  strfullname nvarchar(344)
  strfirstname nvarchar(128)
  strmiddlename nvarchar(128)
  strlastname nvarchar(128)
  strtitle nvarchar(128)
  stremployeeno nvarchar(32)
  dtenter datetime2
  lgender int
  dtbirth datetime2
  strstreet nvarchar(192)
  strpostalcode nvarchar(20)
  strpobox nvarchar(20)
  strcity nvarchar(192)
  strstate nvarchar(64)
  strcountry nvarchar(64)
  strphonebiz nvarchar(80)
  strphonemobilebiz nvarchar(80)
  strphonehome nvarchar(80)
  strphonemobilehome nvarchar(80)
  strphonefax nvarchar(80)
  strphonepager nvarchar(80)
  strmailbiz nvarchar(508)
  strmailhome nvarchar(508)
  strtimezone nvarchar(64)
  lextprimgrpid int
  strextlogin1 nvarchar(80)
  strextpwd1 nvarchar(80)
  strextlogin2 nvarchar(80)
  strextpwd2 nvarchar(80)
  strextlogin3 nvarchar(80)
  strextpwd3 nvarchar(80)
  strdefaultlayout nvarchar(160)
  lproxyperson int
  strimg_contenttype nvarchar(100)
  strimg_filename nvarchar(510)
  strimg_url nvarchar(510)
  strimg_meta nvarchar(4096)
  dtimg_lastmodified datetime2
  strdefaultlang nvarchar(4)
  strdefaultlocale nvarchar(100)
  strname nvarchar(508)
  strguid nvarchar(80)
  bdeleted bit
  bdisabled bit
  strdescription nvarchar(1024)
  countrylong nvarchar(64)
  curr nvarchar(6)
}

Table dbo.website_content {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  txt_content nvarchar(max)
  str_country nvarchar(510)
  ref_a13f4053 int
  str_column nvarchar(510)
  l_position int
  b_hidden bit
  txt_preview nvarchar(max)
  str_modulename nvarchar(510)
  b_module bit
  b_hide_module_title bit
  str_page_section nvarchar(510)
  l_translated_from int
  txt_review_preview nvarchar(max)
}

Table dbo.website_forms {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  txt_formdata nvarchar(max)
  l_pageid int
  str_editfieldtext nvarchar(510)
  str_country nvarchar(510)
  str_subject nvarchar(510)
}

Table dbo.website_newsletter {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_email nvarchar(510)
  str_confirmationcode nvarchar(510)
  dt_confirmedat datetime2
  str_country nvarchar(510)
  was_imported bit
  str_status nvarchar(510)
}

Table dbo.website_pages {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_pagetitle nvarchar(510)
  l_position int
  ref_d38fbecf int
  str_country nvarchar(510)
  str_layout nvarchar(510)
  str_alias nvarchar(510)
  b_hidden bit
  txt_description nvarchar(max)
  txt_keywords nvarchar(max)
  str_metatitle nvarchar(510)
  b_not_standard bit
  str_shortcut nvarchar(510)
  b_kim bit
  str_newsletter_header nvarchar(510)
  str_page_icon nvarchar(510)
  l_translated_from int
  b_submitted_for_review bit
  str_submitted_for_review_by nvarchar(510)
  b_has_preview_content bit
}

Table dbo.website_products {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name nvarchar(max)
  str_bu_country nvarchar(max)
  txt_description nvarchar(max)
  str_type nvarchar(max)
  b_digital bit
  flt_price float
  str_currency nvarchar(max)
  str_language nvarchar(max)
  str_image nvarchar(max)
  l_popularity int
  str_status nvarchar(max)
  str_link nvarchar(max)
  str_unit nvarchar(max)
  str_button_link nvarchar(max)
  str_download_link nvarchar(510)
  str_button_download_link varchar(255)
  int_order_product int
}

Table dbo.website_products_sectors {
  lid int
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.website_products_solutions {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.website_products_sub_sector {
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
  lid PK
}

Table dbo.website_sectors {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  b_disabled bit
  str_image nvarchar(max)
  str_name nvarchar(max)
  str_type nvarchar(max)
  str_bu_country nvarchar(100)
}

Table dbo.website_solutions {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  b_disabled bit
  str_image nvarchar(max)
  str_name nvarchar(max)
  str_type nvarchar(max)
  str_bu_country nvarchar(100)
}

Table dbo.website_sub_sector {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name nvarchar(510)
  str_image nvarchar(max)
  b_disabled bit
  str_bu_country nvarchar(100)
}

Table dbo.withholding_taxes {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_description nvarchar(510)
  str_currency nvarchar(510)
  flt_value float
  ref_f1c82cb6 int
}

Table dbo.xdatagroup01c77d95 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_identifier_229526fc nvarchar(510)
  str_value_35ceb3f9 nvarchar(510)
  str_project_5a849da5 nvarchar(510)
  str_targetcountry nvarchar(510)
  ref_b0e40b92 int
  fklid int
}

Table dbo.xdatagroup056d1a11 {
  fklid int
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  dt_anmeldedatumdateti_5c565f3f datetime2
  str_bemerkungshorttex_1b117165 nvarchar(510)
  str_dummyansprechpart_b6c12aa0 nvarchar(510)
  str_dummyseminarshort_3372325c nvarchar(510)
  dt_dummyvondatetime_087cd822 datetime2
  l_intangemeldetintege_555e94d8 int
  l_intgeblocktinteger_c06cd189 int
  l_intwartelisteintege_e1ad1a8e int
  str_land_5f1748a4 nvarchar(510)
  str_rabattshorttext_8045fb73 nvarchar(510)
  str_statusshorttext_7aaca077 nvarchar(510)
  ref_d0e403fe int
  ref_21cf433f int
  str_extraenddetails_f83eb0ae nvarchar(510)
  str_ccemail_d7d4e286 nvarchar(510)
  flt_regprice_f1841556 float
  str_regcurrency_ae57e64d nvarchar(510)
  dt_confirmationsentat_231fbdaa datetime2
  str_specialrecognitio_987bb330 nvarchar(510)
  str_azwvarbeitsagentu_722b78c0 nvarchar(510)
  b_azwvarbeitslos_52ed29fb bit
  b_azwvbezahlt_49f897e9 bit
  str_azwvbgsnr_7a72c0c9 nvarchar(510)
  dt_azwvbezahltam_f986a252 datetime2
  b_azwv_d5fbab0d bit
  b_invoiced bit
  txt_time nvarchar(max)
  dt_checkout datetime2
  str_accompanied nvarchar(510)
  ref_81009404 int
  str_brings_spouse nvarchar(510)
  str_aaeaftertraining nvarchar(510)
  txt_observation nvarchar(max)
  str_singleroom nvarchar(510)
  str_doubleroom nvarchar(510)
  str_freetext nvarchar(510)
  str_certificate_url nvarchar(max)
  txt_txt_json nvarchar(max)
  flt_discount float
}

Table dbo.xdatagroup06b81eb6 {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  dt_vondatumuhrzeit_359eb122 datetime2
  dt_bisdatumuhrzeit_10f4d4e7 datetime2
  str_reiseweg_8b10bdb1 nvarchar(510)
  txt_bemerkung_2147fd54 nvarchar(max)
  ref_f785cd44 int
  str_benutzer_1f065465 nvarchar(510)
  ref_44426b54 int
  b_geprft_710bf532 bit
  flt_summe_c6b4be0e float
  flt_summebelege_37539557 float
  flt_summepauschalen_a433dba9 float
  flt_mileage float
  b_invoiced bit
  dt_paidat datetime2
  str_aprovedby nvarchar(510)
}

Table dbo.xdatagroup17bd9dde {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.xdatagroup1cbaedf3 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_po_number nvarchar(510)
  txt_description nvarchar(max)
  dt_po_date datetime2
  ref_f1ba868c int
  ref_3315e1c6 int
  b_invoiced bit
}

Table dbo.xdatagroup1cd09765 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_companygroupname nvarchar(510)
  l_noofemployees int
  str_website nvarchar(510)
  str_groupstatus nvarchar(510)
  str_lastsearch nvarchar(510)
  flt_revenue float
  bdlcguid nvarchar(510)
  b_show_on_mnc bit
}

Table dbo.xdatagroup353ea8c1 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.xdatagroup3af27936 {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  str_industry_fc994ef5 nvarchar(510)
  ref_46984757 int
  bdlcguid nvarchar(510)
}

Table dbo.xdatagroup3cf9152f {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_name_0a24610c nvarchar(510)
  str_colorcode_db475e72 nvarchar(510)
}

Table dbo.xdatagroup44427259 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_actionpoint nvarchar(510)
  str_who nvarchar(510)
  dt_when datetime2
  str_status nvarchar(510)
}

Table dbo.xdatagroup453e0d78 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_country_86985d78 nvarchar(510)
  ref_2495e2e9 int
  ref_f57e8322 int
  flt_taxrate_421987d1 float
  dt_invoicedate_4a240615 datetime2
  flt_skonto_fd20ada6 float
  dt_paidat_64d8ff76 datetime2
  ref_05e7a867 int
  str_freetextfieldtobe_1784c90c nvarchar(510)
  flt_total_ea7c2ad4 float
  txt_companyaddress_d6abdeeb nvarchar(max)
  str_ordernumber_2914a54b nvarchar(510)
  str_paymentconditions_cfb63a9f nvarchar(510)
  str_invoiceno_24f6eada nvarchar(510)
  str_invoicecategory_51c431a9 nvarchar(510)
  str_targetcountry_1ce8b59f nvarchar(510)
  str_currency_d88548f8 nvarchar(510)
  b_withouttax_e9c2d98d bit
  b_paid_1b38edcd bit
  b_notonreconc_88093ca0 bit
  b_isreconciliationinv_cff1a5c8 bit
  b_exported bit
  dt_forecast_b2be56f2 datetime2
  str_comment_e1677d4d nvarchar(510)
  flt_amountpaid_8fb53d6b float
  str_vatno_d286cbd7 nvarchar(510)
  b_resume_47cb2a56 bit
  str_accountpaidto_9b32db90 nvarchar(510)
  b_logo bit
  dt_maturity_date datetime2
  dt_payment_reminder_1 datetime2
  dt_payment_reminder_2 datetime2
  dt_payment_reminder_3 datetime2
  dt_payment_reminder_4 datetime2
  txt_lastwarning_comment nvarchar(max)
  l_fileinformation int
  l_daysmaturitydate int
  b_test bit
  b_merge_exp_cons_on_export bit
  b_print_expenses_report bit
  b_is_office_invoice bit
  str_transaction_id nvarchar(510)
  b_manual_expenses bit
  flt_withholding_tax_value float
  str_withholding_tax_description nvarchar(510)
  ref_90d03836 int
  l_resumebyaccount int
  b_is_passthrough_invoice bit
  str_hash nvarchar(510)
  str_pdf_url nvarchar(510)
  txt_txt_json nvarchar(max)
  qb_id nvarchar(510)
  b_inside_eu bit
  net_total float
  str_passthrough_reason nvarchar(max)
}

Table dbo.xdatagroup455ae863 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  flt_days_754f7ee3 float
  str_consultant_8c8d0790 nvarchar(510)
  l_year_698c6a1c int
}

Table dbo.xdatagroup5a7e1860 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  dt_itemdate_0f0b0554 datetime2
  flt_amount_bf759338 float
  str_typeofrevenue_634f9642 nvarchar(510)
  str_country_ac89d580 nvarchar(510)
  str_comment_7eb8d793 nvarchar(510)
  str_currency_fe7a8d15 nvarchar(510)
}

Table dbo.xdatagroup5f99096f {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  txt_consultants_8fe8f911 nvarchar(max)
  dt_from_5a6fba9c datetime2
  dt_to_7679503f datetime2
  l_datediff_3a0fa035 int
  str_myname_a3469681 nvarchar(510)
  str_filtername_c40707ff nvarchar(510)
}

Table dbo.xdatagroup6b5f2644 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  dt_belegdatum_c4a6f58a datetime2
  str_beschreibung_0944335a nvarchar(510)
  flt_betrag_bcafa9c9 float
  str_currency_996c23db nvarchar(510)
  str_kostenart_b16c5fcc nvarchar(510)
  str_artderbewirtung_1ab78a55 nvarchar(510)
  b_frhstck_c4d77b17 bit
  str_land_3999937b nvarchar(510)
  str_projectcode_d55281c2 nvarchar(510)
  dt_bewirtungab_31a776c2 datetime2
  dt_bernachtungab_2bdf851b datetime2
  flt_wechselkurs_c6c00d47 float
  flt_betragineuro_41fca5ef float
  str_steuersatz_495138d5 nvarchar(510)
  b_invoiceclient bit
  str_invoicescope nvarchar(510)
  b_invoiced bit
  str_hotelname nvarchar(510)
  str_hotelcity nvarchar(510)
  b_automatic bit
}

Table dbo.xdatagroup6bfb60a3 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_accountheading_9f963075 nvarchar(510)
  str_accountno_7edd0dac nvarchar(510)
  str_country_07530cfe nvarchar(510)
}

Table dbo.xdatagroup74a2b33e {
  lid PK
  luserid int
  dtedit datetime2
  luseridinsert int
  dtinsert datetime2
  str_berater_bd95f5e6 nvarchar(510)
  str_email_0d53e211 nvarchar(510)
  str_fax_3ba390b5 nvarchar(510)
  str_firma_037e76ad nvarchar(510)
  str_land_72affc1e nvarchar(510)
  str_ort_1459a121 nvarchar(510)
  str_plz_e337c888 nvarchar(510)
  str_postfach_b41558b6 nvarchar(510)
  str_strasse_601a367c nvarchar(510)
  str_telefon_40945b96 nvarchar(510)
  str_web_c294c20b nvarchar(510)
  str_addname_2c777d35 nvarchar(510)
  str_countryin_44e48b89 nvarchar(510)
  str_region_4a7bf0eb nvarchar(510)
  str_province_a608a56c nvarchar(510)
  str_vatno_05638d31 nvarchar(510)
  l_noofemployees_03590eb4 int
  str_product_548ca731 nvarchar(510)
  str_fatt_d035837e nvarchar(510)
  str_importance_78155e3a nvarchar(510)
  str_profile_b7100cf3 nvarchar(510)
  str_tsm_4d7ac75f nvarchar(510)
  str_tpm_f64563f3 nvarchar(510)
  str_tfm_f5dcdd16 nvarchar(510)
  str_kaizen_df5b6c35 nvarchar(510)
  str_countryin2letters_8ad7d92a nvarchar(510)
  str_extcustomerno_44a14c9a nvarchar(510)
  str_paymentconditions_d54ed938 nvarchar(510)
  str_multinationalcomp_71dbe58d nvarchar(510)
  str_regionitaly_30c1a030 nvarchar(510)
  str_campaign_0a9e2285 nvarchar(510)
  ref_ba6b13a7 int
  ref_29061ad8 int
  txt_invoiceaddress nvarchar(max)
  txt_invoicedeliveryaddress nvarchar(max)
  str_howinvoiceshouldbesent nvarchar(510)
  b_ponumberismandatory bit
  txt_financialcomment nvarchar(max)
  str_contracts_responsible nvarchar(510)
  str_other_leadsource nvarchar(510)
  bdlcguid nvarchar(510)
  str_invoice_company_group nvarchar(510)
  str_codebasefornewprojects nvarchar(510)
  str_fiscalcode nvarchar(510)
  str_quickbooks_realmid nvarchar(510)
  b_is_ki_company bit
  ref_rsu int
  str_ki_name nvarchar(510)
  str_macro_sector nvarchar(max)
  b_employee_based bit
  b_disabled bit
  str_customer_engagement_rep nvarchar(510)
  str_hubspot_domain nvarchar(200)
}

Table dbo.xdatagroup8559bb4d {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.xdatagroup86fd9c45 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.xdatagroup8bda859c {
  fklid int
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_dummykategoriesho_37d90ae3 nvarchar(510)
  str_land_d99f911e nvarchar(510)
  str_seminartitelshort_efff5d95 nvarchar(510)
  versionupdate datetime2
  txt_websiteseminardescription nvarchar(max)
  txt_goals nvarchar(max)
  txt_program nvarchar(max)
  txt_seminardescription nvarchar(max)
  txt_targetgroup nvarchar(max)
  str_codestart4letters nvarchar(510)
  txt_seminar_image nvarchar(max)
  l_education_kaizen_course int
}

Table dbo.xdatagroup99370602 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_month_5ae327f0 nvarchar(510)
  str_country_79764270 nvarchar(510)
  str_businesssector_ffdbaa3d nvarchar(510)
  str_year_90330bbd nvarchar(510)
  flt_amount_45665fa7 float
}

Table dbo.xdatagroupb352e99b {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  dt_reisetag_2877bf26 datetime2
  str_currency_f1f12d1b nvarchar(510)
  str_reiseweg_8d242921 nvarchar(510)
  ref_fcf11ec1 int
  ref_3563d402 int
  flt_stunden_44830cab float
  flt_pauschale_eb43d7c2 float
  flt_mileage float
  b_invoiced bit
  b_breakfast bit
  b_dinner bit
  b_lunch bit
  b_nomeals bit
}

Table dbo.xdatagroupb42ad6bd {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_nameofthetemplate_3bb445b3 nvarchar(510)
  str_country_3bff6374 nvarchar(510)
  b_deactivated bit
  str_connected_flow nvarchar(510)
  l_use_flow_after_lid int
}

Table dbo.xdatagroupb508677a {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.xdatagroupb65314a3 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_lid int
  l_id int
}

Table dbo.xdatagroupbbea6600 {
  lid PK
  dtinsert datetime2
  luseridinsert int
  dtedit datetime2
  luserid int
  str_country_0e40f7a0 nvarchar(510)
  str_code_d1f00062 nvarchar(510)
  str_region_314cd119 nvarchar(510)
  b_coveredbyki_3fc065a9 bit
  str_2lettercode_acbf5ddf nvarchar(510)
  str_2letterlc_8ac7e303 nvarchar(510)
  str_currency_5f64230d nvarchar(510)
  str_baseoffset_e1748c13 nvarchar(510)
  str_dynamicsmandant_64257e3a nvarchar(510)
  flt_defaulttaxrate_d59e5fda float
  str_projectend_c048656a nvarchar(510)
  l_crmbuaddress_c42d622f int
  str_mainlanguage_6b125bbd nvarchar(510)
  str_locallanguagename nvarchar(510)
  str_economicarea nvarchar(510)
}

Table dbo.xdatagroupc0def29a {
  fklid int
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luserid int
  luseridinsert int
  str_axaptacodeshortte_5917febe nvarchar(510)
  str_bemerkungshorttex_68863a68 nvarchar(510)
  str_betriebsstatussho_59dd6bf4 nvarchar(510)
  flt_bezteilnehmerfloa_458f3104 float
  dt_bisdatetime_661e6f97 datetime2
  dt_checkindatetime_3f36d56f datetime2
  dt_checkoutdatetime_819814a7 datetime2
  str_codeshorttext_3cc3f149 nvarchar(510)
  str_dummypraxisref1sh_80cd2dec nvarchar(510)
  str_dummypraxisref2sh_5db22ef1 nvarchar(510)
  str_dummyseminartitel_3937ebe4 nvarchar(510)
  l_erforderlicheteilne_502f41e8 int
  l_maxteilnehmerintege_49410e50 int
  str_praxisreferent1sh_abaa0c9b nvarchar(510)
  str_praxisreferent2sh_95212768 nvarchar(510)
  str_praxis1emailshort_ad0fddf1 nvarchar(510)
  str_praxis1firmashort_10dbdaff nvarchar(510)
  str_praxis1telshortte_21c51a7d nvarchar(510)
  str_praxis2emailshort_04ca169c nvarchar(510)
  str_praxis2firmashort_e1aebd47 nvarchar(510)
  str_praxis2telshortte_d3ea5571 nvarchar(510)
  flt_preisdzfloat_3f1b8a7e float
  flt_preisezfloat_5fee95b5 float
  l_raumgreinteger_8e8e230a int
  str_referent1shorttex_84588e0a nvarchar(510)
  str_referent2shorttex_f8d62585 nvarchar(510)
  str_seminarstatusshor_555a724d nvarchar(510)
  str_statusref1shortte_065b7057 nvarchar(510)
  str_statusref2shortte_2025d57d nvarchar(510)
  b_stornoboolean_218fda1a bit
  dt_vondatetime_9401ef2a datetime2
  str_empfngerbccshortt_e19cd264 nvarchar(510)
  str_whrung_7fe9f478 nvarchar(510)
  str_land_724660d8 nvarchar(510)
  ref_f1dd3420 int
  ref_c0d6237e int
  txt_emailbodylongtext_52f53739 nvarchar(max)
  str_extraforenddetail_cfb56a6f nvarchar(510)
  flt_seminarprice_b83faf02 float
  str_semcurrency_5363fda5 nvarchar(510)
  str_azwvmassnahmennr_fa544d1c nvarchar(510)
  str_azwvveranstaltung_b67b8240 nvarchar(510)
  flt_azwvstundenzahl_dc3b9dc1 float
  flt_azwvkursnetgebueh_ec6bc003 float
  l_unnamedparticipants_258857b7 int
  clientvoice nvarchar(max)
  b_intheoffice_1e12bf0d bit
  str_city nvarchar(510)
  str_country nvarchar(510)
  str_addlanguage nvarchar(510)
  b_showwebsite bit
  b_addlangonly bit
  l_additionalfilefo int
  l_agendafile_35ff7 int
  l_extrafileforendd int
  b_test bit
  ref_4466c2e7 int
  b_hide_info bit
  flt_tax float
  str_talentlms_connection nvarchar(max)
  str_online_link nvarchar(max)
  str_teams_meeting_id nvarchar(max)
  str_time_zone_offset nvarchar(100)
  b_online_learning bit
  str_time_observation nvarchar(510)
}

Table dbo.xdatagroupd13d0714 {
  fklid int
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  str_consultant_21c18580 nvarchar(510)
  flt_price_73c5a946 float
  b_consider_for_unreported bit
}

Table dbo.xdatagroupd368540c {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_landregion_35e38528 nvarchar(510)
  str_landregion2letter_dc786ccf nvarchar(510)
  flt_verpflpausch24h_5fa0a807 float
  flt_verpflpausch14h_7fe71d47 float
  flt_verpflpausch8h_a2cb9f42 float
  flt_bernachstungspaus_138dd14f float
  str_whrung_93acec62 nvarchar(510)
}

Table dbo.xdatagroupd8b41609 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  dt_date_4da7192d datetime2
  str_projectcode_1edab67a nvarchar(510)
  str_consultant_065a1337 nvarchar(510)
  str_comment_6a077ffd nvarchar(510)
  str_status_38f452a0 nvarchar(510)
  str_country_0ba53905 nvarchar(510)
  str_nodays_06c3897f nvarchar(510)
  changekey nvarchar(510)
  id nvarchar(1000)
  str_counttocountry_d3874f83 nvarchar(510)
  b_invoiced_d146bf3a bit
  l_type int
  ref_93e27796 int
  ref_a8b1e944 int
  flt_expense_cost float
  flt_mileage float
  str_route nvarchar(510)
  str_transporttype nvarchar(510)
  str_currency nvarchar(510)
  b_expense_invoiced bit
  str_maintool nvarchar(510)
  ref_3279b082 int
  dt_to datetime2
  str_role nvarchar(510)
  flt_rate float
  str_approved_status nvarchar(510)
  str_afternoon_or_morning nvarchar(max)
  str_start_hours nvarchar(max)
  str_end_hours nvarchar(max)
  str_rest_from nvarchar(max)
  str_rest_to nvarchar(max)
  str_deliver_mode nvarchar(max)
  str_for_free_reason nvarchar(max)
  series_master_id nvarchar(510)
  str_invoice_type nvarchar(200)
  str_delivery_country nvarchar(510)
  str_show_as varchar(10)
}

Table dbo.xdatagroupda72b87b {
  fklid int
  lid PK
  luserid int
  dtedit datetime2
  luseridinsert int
  dtinsert datetime2
  str_abteilung_124cc83c nvarchar(510)
  str_anrede_a6b0911f nvarchar(510)
  b_deaktiviert_b1e28985 bit
  str_email_eed32544 nvarchar(510)
  str_fax_a6bb22cd nvarchar(510)
  dt_geburtstag_d7f90eeb datetime2
  str_land_93e0de56 nvarchar(510)
  str_mobil_de7736ed nvarchar(510)
  str_nachname_fff19fc5 nvarchar(510)
  str_position_dc9bc2b5 nvarchar(510)
  str_telefon_c6fbf9e5 nvarchar(510)
  str_telefonprivat_fbda9e00 nvarchar(510)
  str_titel_e7e1e57a nvarchar(510)
  str_vorname_bf23ae6d nvarchar(510)
  dt_managermatrix_47f66537 datetime2
  b_decisionmaker_40ca4427 bit
  str_secretaryname_a9db413f nvarchar(510)
  str_secretaryemail_4893722e nvarchar(510)
  str_secretaryphone_fa06646e nvarchar(510)
  txt_bemerkungen_51744330 nvarchar(max)
  txt_verteiler_b1ab8fcf nvarchar(max)
  str_engagementmanager_b48b79d5 nvarchar(510)
  l_seccode int
  ref_b3272824 int
  txt_priaddress_b078c2e3 nvarchar(max)
  str_pricity_3b196a9f nvarchar(510)
  str_pricountryin_068d81b8 nvarchar(510)
  str_pristate_46e3b136 nvarchar(510)
  str_prizip_5b9187b7 nvarchar(510)
  str_othcity_e22692a9 nvarchar(510)
  str_othzip_858ce30d nvarchar(510)
  str_othcountryin_c39525e0 nvarchar(510)
  str_othstate_1692e835 nvarchar(510)
  txt_othaddress_5f139fb5 nvarchar(max)
  str_reportsto_cc03066e nvarchar(510)
  str_assignedto_18c5b1d7 nvarchar(510)
  str_nicknameotherfirs_e0e26f20 nvarchar(510)
  dt_startdate_75ba8d3f datetime2
  ref_a18b7eef int
  str_forwardemail nvarchar(510)
  b_financialcontact bit
  l_file_c37b4c98 int
  l_photo_5200e362 int
  str_clpool nvarchar(510)
  b_doublelumpsum bit
  b_ki_em_warning bit
  flt_skill_matrix_score float
  ref_b65e58c2 int
  dt_end_date datetime2
  bdlcguid nvarchar(510)
  str_add_to_country_newsletter nvarchar(510)
  str_office_profile nvarchar(510)
  flt_cost float
  str_reason_for_leave nvarchar(510)
  str_cv_file nvarchar(max)
  str_industry nvarchar(max)
  str_macro_sector nvarchar(max)
  flt_hours_per_week float
  b_year_commitment bit
  flt_amount_per_km float
  ref_startingpointlid int
  str_gender nvarchar(100)
  str_termination_reason nvarchar(510)
  b_is_business_owner_member bit
  b_is_credit_card_member bit
  b_is_nonrefundable bit
  str_kms_currency nvarchar(100)
  ref_travelperk_id int
  b_is_qatar_id bit
  b_has_company_car bit
}

Table dbo.xdatagroupdc03d9cd {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  str_country_a31a87af nvarchar(510)
  str_costtype_28409a20 nvarchar(510)
}

Table dbo.xdatagroupde529862 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  l_id int
}

Table dbo.xdatagroupdf856a4c {
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  str_currency_0d97ff77 nvarchar(510)
  dt_date_44e73cba datetime2
  flt_exchangeratetoeur_64ccc60a float
}

Table dbo.xdatagroupe9a240bb {
  fklid int
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  dt_paydate_e36863c3 datetime2
  flt_amount_1f4aacfd float
  str_currency_18750523 nvarchar(510)
  str_country_7fcd931e nvarchar(510)
  b_invoiced bit
  str_comment nvarchar(510)
  ref_c0b4cb5a int
  str_financial_comment nvarchar(510)
  b_variable_fixed_payment bit
  b_ki_online_special_rate bit
  flt_gampart float
  str_gamcountry nvarchar(510)
  str_country_of_delivery nvarchar(max)
  str_revenue_type nvarchar(max)
}

Table dbo.xdatagroupf3be2299 {
  lid PK
  fklid int
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  dt_date_16d07635 datetime2
  str_descsription_b6e5a8cd nvarchar(5100)
  str_consultant_1573e253 nvarchar(510)
  flt_quantity_604db5e8 float
  flt_amount_7b435fb8 float
  str_category_b3337bd5 nvarchar(510)
  flt_taxrate_cbfdfdfd float
  ref_813981e4 int
  fixeditem bit
  l_itemref int
  str_revenue_type nvarchar(max)
  str_unit nvarchar(max)
  flt_passthrough float
}

Table dbo.xdatagroupf957bc73 {
  lid PK
  luserid int
  luseridinsert int
  dtedit datetime2
  dtinsert datetime2
  dt_dateofbill_231dc62c datetime2
  str_projectcode_fe522c1f nvarchar(510)
  flt_amount_0dc4ef51 float
  str_currency_eade6177 nvarchar(510)
  str_comment_cca46fd7 nvarchar(510)
  str_consultant_21834a0e nvarchar(510)
  ref_6704352a int
  ref_8ee4bf69 int
  str_artderbewirtung_92858052 nvarchar(510)
  dt_bernachtung_3ee93282 datetime2
  b_frhstck_94d9ccf0 bit
  flt_mileage_32fb51ef float
  str_country_eaebc887 nvarchar(510)
  invoiced bit
  l_distance_20332086 int
  l_fileuploadbillsc int
  str_status nvarchar(510)
  b_billable bit
  dt_expense_paid_at datetime2
  ref_6379178d int
  flt_amount2 float
  str_currency2 nvarchar(510)
  dt_submission_date datetime2
  txt_image_url nvarchar(max)
  txt_reject_reason nvarchar(max)
  ref_planner_lid int
  ref_veryfi_id int
  b_is_tax bit
  flt_veryfi_tax_amount float
  ref_veryfi_id_duplicateof int
  flt_amount_km_member float
  flt_mileage_override_new float
  flt_amount_in_user_currency float
  str_veryfi_invoicenumber nvarchar(510)
  ref_kim_ids_duplicateof nvarchar(510)
  flt_max_amount float
  str_max_amount_currency nvarchar(510)
  b_not_duplicated smallint
  str_override_zip_code nvarchar(200)
  str_override_city nvarchar(400)
  str_starting_zip nvarchar(200)
  str_starting_city nvarchar(510)
  str_destination_zip nvarchar(200)
  str_destination_city nvarchar(510)
  tolls float
  flt_receipt_km_distance float
  str_receipt_route nvarchar(max)
  str_admin_note nvarchar(max)
  flt_tolls_from_override float
  flt_kms_from_override float
  str_standard_wrong_reason nvarchar(510)
  str_tripe_type nvarchar(100)
  txt_deleted_reason varchar(max)
  str_starting_zip_correction nvarchar(500)
  str_starting_city_correction nvarchar(500)
  str_destination_zip_correction nvarchar(500)
  str_destination_city_correction nvarchar(500)
  flt_kms_correction float
  flt_amount_correction float
  str_trip_type_correction nvarchar(100)
  dt_close_date_correction datetime2
  ref_tolls_expense int
  str_new_where_to_deliver varchar(255)
  l_distance_in_miles float
  bool_is_converted int
  str_general_reject_reason nvarchar(510)
  str_reject_reason_specific nvarchar(510)
  flt_distance_start_to_invoice_delivery float
  str_expense_location varchar(255)
}

Table dbo.xtable423058f8 {
  note: "Projects_table"
  lid PK
  dtedit datetime2
  dtinsert datetime2
  luseridinsert int
  luserid int
  str_status_2aafe888 nvarchar(510)
  str_company_5a8bb18b nvarchar(510)
  str_city_2ef91f28 nvarchar(510)
  dt_queryfrom_e3c0d077 datetime2
  str_newcustomer_66c2e14f nvarchar(510)
  str_businesssegment_c7f65f1c nvarchar(510)
  str_projectcode_5ce8fc74 nvarchar(510)
  str_engagementmanager_0507a708 nvarchar(510)
  dt_proposalsentat_9d58deb7 datetime2
  flt_daysoffered_fdd89e8a float
  dt_contractconfirmeda_70cf1637 datetime2
  dt_projectcompletedat_94b628be datetime2
  dt_cancellationat_6ae1a097 datetime2
  str_reasonforcancella_d2663c39 nvarchar(510)
  ref_071edd0d int
  str_soldby_7f469c28 nvarchar(510)
  flt_dayrate_30f23b59 float
  str_kicountry_2201e39b nvarchar(510)
  str_zipcode_ea4254aa nvarchar(510)
  l_companyid_f20681fb int
  str_contact_112f012d nvarchar(510)
  str_currency_f5003e92 nvarchar(510)
  str_wheretodeliver_a889bae9 nvarchar(510)
  str_soldby2_8b82394a nvarchar(510)
  flt_expensesperday_6a0b0159 float
  str_paymentconditions_4b4fcbe3 nvarchar(510)
  str_ordernumber_607a94e4 nvarchar(510)
  str_costcenter_e1378158 nvarchar(510)
  txt_invoiceaddress_c07ae622 nvarchar(max)
  l_frlid_ef02bc67 int
  l_prlid_aaeb7d8d int
  dt_bdgday_2783b238 datetime2
  ref_15cf77be int
  txt_comment2_c9ed78bf nvarchar(max)
  str_customerrelations_b05f45b1 nvarchar(510)
  str_cancellationreaso_7b8b3f99 nvarchar(510)
  str_taxnumber_d838c837 nvarchar(510)
  str_projectphase_18fbb5cc nvarchar(510)
  flt_mileage_e95e8d17 float
  str_proposalpresented_d4d62fc5 nvarchar(510)
  b_gembavisittoanother_04652e0f bit
  str_prfirstname_db833562 nvarchar(510)
  str_prlastname_ca9fe94b nvarchar(510)
  str_premail_3c48ac4a nvarchar(510)
  str_prphone_8d0a52e5 nvarchar(510)
  str_frfirstname_d44b4172 nvarchar(510)
  str_frlastname_fe50a032 nvarchar(510)
  str_fremail_2473860b nvarchar(510)
  str_frphone_674c6d93 nvarchar(510)
  txt_followupactions_259b6728 nvarchar(max)
  b_createdinaccounting_64b0c17d bit
  txt_comment_f33f77c4 nvarchar(max)
  flt_projectvalue_c5fb2ec4 float
  b_inallprobability_9508335b bit
  flt_sold1percentage_6b4639cb float
  flt_sold2percentage_d9472e34 float
  str_soldby1country_cce402bb nvarchar(510)
  str_soldby2country_b15b7ea3 nvarchar(510)
  b_fixedpriceproject_749f8160 bit
  str_salessupervisor_12cc4add nvarchar(510)
  flt_estimatedvalueoft_2d34503a float
  txt_internationalcoun_07aafb66 nvarchar(max)
  b_sendinvoicetoanothe_e4106afb bit
  str_assignedto_4ae88b8b nvarchar(510)
  str_cityofdelivery_3d6f6588 nvarchar(510)
  b_regionalfocus bit
  dt_end datetime2
  flt_expected_financial_gain float
  flt_actual_financial_gain float
  str_invoicecicle nvarchar(510)
  ref_cbf42b66 int
  txt_financialcomment nvarchar(max)
  str_howinvoiceshouldbesent nvarchar(510)
  b_ponumberismandatory bit
  txt_invoicedeliveryaddress nvarchar(max)
  b_variable_expenses bit
  str_invoicedby nvarchar(510)
  l_contract int
  l_proposal_01c040e int
  l_fileinformation int
  str_group nvarchar(510)
  str_industry nvarchar(510)
  b_financial_reviewed bit
  flt_expectedvariable float
  b_test bit
  b_warn_not_allowed_country bit
  b_warn_not_allowed_consultant bit
  dt_po_request_date datetime2
  dt_poresponsedate datetime2
  dt_contract_sent_date datetime2
  dt_contract_response_date datetime2
  str_account_manager nvarchar(510)
  flt_accountmanagerperc float
  str_accountmanagercountry nvarchar(510)
  str_accounting_responsible nvarchar(510)
  txt_contracts_comment nvarchar(max)
  dt_nextstep datetime2
  b_periodic_po bit
  flt_default_hourly_rate float
  txt_title nvarchar(max)
  txt_before_figure nvarchar(max)
  txt_after_figure nvarchar(max)
  str_share_data_public nvarchar(510)
  dt_start datetime2
  l_probability1 int
  l_probability2 int
  flt_total_external_cost float
  flt_actualdays float
  b_cancelscript bit
  str_connected_to_project nvarchar(510)
  b_po_contract_optional bit
  str_team nvarchar(510)
  b_is_variable_fee bit
  b_connected_to_variable_fee_projec bit
  str_lead_source nvarchar(510)
  b_files_collected bit
  proposal_file_url nvarchar(max)
  contract_file_url nvarchar(max)
  query_file_url nvarchar(max)
  str_macro_sector nvarchar(max)
  flt_delivery_budget float
  str_mnc_focused nvarchar(100)
  str_business_area nvarchar(510)
  dt_nda_sent datetime2
  dt_nda_received datetime2
  flt_km_per_project float
  ref_startingpointlid int
  dt_expected_contract_confirmed datetime2
  str_customer_engagement_rep nvarchar(510)
  flt_non_business float
  b_bridge_25_abril bit
  b_is_large_account_project bit
  str_custom_toll nvarchar(510)
  ref_invoiced_by int
}

Table dbo.xtablee1abc02f {
  lid PK
  dtedit datetime2
  luserid int
  dtinsert datetime2
  luseridinsert int
  str_companyname_825b9c66 nvarchar(510)
  str_address1_2e84de8d nvarchar(510)
  str_address2_2f807757 nvarchar(510)
  str_zipcode_e8320262 nvarchar(510)
  str_city_2748c718 nvarchar(510)
  str_phone_2d0a7439 nvarchar(510)
  str_fax_3069a559 nvarchar(510)
  str_mail_b1f9666c nvarchar(510)
  str_country_09f23255 nvarchar(510)
  str_state_eb92dcaa nvarchar(510)
  str_2lettercountrycod_6381529c nvarchar(510)
  str_region nvarchar(510)
  str_domain nvarchar(510)
}

// Relationships

Ref: dbo.website_products_sectors.l_id > dbo.website_sectors.lid
Ref: dbo.website_products_sectors.fklid > dbo.website_products.lid
Ref: dbo.planner_configlink.ref_385db616 > dbo.dsuser.lid
Ref: dbo.xdatagroup17bd9dde.fklid > dbo.casestudies_db.lid
Ref: dbo.receipts_emails_expenses.ref_expense > dbo.xdatagroupf957bc73.lid
Ref: dbo.extracted_tolls.fklid > dbo.starting_point_tolls_details.lid
Ref: dbo.xdatagroupe9a240bb.ref_c0b4cb5a > dbo.xdatagroup453e0d78.lid
Ref: dbo.xdatagroupe9a240bb.fklid > dbo.xtable423058f8.lid
Ref: dbo.xdatagroupda72b87b.ref_startingpointlid > dbo.bu_rsu_starting_points.lid
Ref: dbo.helpdesk_activity.fklid > dbo.helpdesk_ticket.lid
Ref: dbo.employee_member_type.l_id > dbo.member_types.lid
Ref: dbo.employee_member_type.fklid > dbo.xdatagroupda72b87b.lid
Ref: dbo.xdatagroupb352e99b.ref_3563d402 > dbo.xtable423058f8.lid
Ref: dbo.xdatagroupb352e99b.ref_fcf11ec1 > dbo.xdatagroupd368540c.lid
Ref: dbo.xdatagroupb352e99b.fklid > dbo.xdatagroup06b81eb6.lid
Ref: dbo.project_business_areas.l_id > dbo.business_areas.lid
Ref: dbo.project_business_areas.fklid > dbo.xtable423058f8.lid
Ref: dbo.xdatagroup06b81eb6.ref_f785cd44 > dbo.xtable423058f8.lid
Ref: dbo.xdatagroup06b81eb6.ref_44426b54 > dbo.xdatagroupd368540c.lid
Ref: dbo.xdatagroup74a2b33e.ref_rsu > dbo.xdatagroup74a2b33e.lid
Ref: dbo.xdatagroupc0def29a.fklid > dbo.xdatagroup8bda859c.lid
Ref: dbo.consultants_hourly_rate.fklid > dbo.xtable423058f8.lid
Ref: dbo.users_licenses.fklid > dbo.xdatagroupda72b87b.lid
Ref: dbo.users_licenses.l_project_lid > dbo.xtable423058f8.lid
Ref: dbo.users_licenses.l_id > dbo.office_licenses.lid
Ref: dbo.cvs_academics.fklid > dbo.cvs_personal_data.lid
Ref: dbo.kim_team_members.fklid > dbo.kim_teams.lid
Ref: dbo.kim_team_members.lemployee_lid > dbo.xdatagroupda72b87b.lid
Ref: dbo.xdatagroup3af27936.ref_46984757 > dbo.casestudies_mainsectors.lid
Ref: dbo.projects_starting_points_km.ref_startingpoints > dbo.bu_rsu_starting_points.lid
Ref: dbo.projects_starting_points_km.fklid > dbo.xtable423058f8.lid
Ref: dbo.xdatagroup056d1a11.ref_21cf433f > dbo.xdatagroupda72b87b.lid
Ref: dbo.xdatagroup056d1a11.fklid > dbo.xdatagroupc0def29a.lid
Ref: dbo.xdatagroup056d1a11.ref_81009404 > dbo.xdatagroupf3be2299.lid
Ref: dbo.website_products_sub_sector.l_id > dbo.website_sub_sector.lid
Ref: dbo.website_products_sub_sector.fklid > dbo.website_products.lid
Ref: dbo.withholding_taxes.fklid > dbo.xdatagroupbbea6600.lid
Ref: dbo.withholding_taxes.ref_f1c82cb6 > dbo.xdatagroup6bfb60a3.lid
Ref: dbo.co2_generaltype_specific_map.general_type_id > dbo.co2_emission_general_types.lid
Ref: dbo.co2_generaltype_specific_map.specific_type_id > dbo.co2_emission_specific_types.lid
Ref: dbo.hubspot_merge_group_companies.fklid > dbo.hubspot_merge_groups.lid
Ref: dbo.excluded_days.ref_e21519c4 > dbo.xdatagroupd8b41609.lid
Ref: dbo.co2_expenses_metadata.ref_co2_single_emission > dbo.co2_single_emissions.lid
Ref: dbo.co2_expenses_metadata.fklid > dbo.xdatagroupf957bc73.lid
Ref: dbo.website_products_solutions.l_id > dbo.website_solutions.lid
Ref: dbo.website_products_solutions.fklid > dbo.website_products.lid
Ref: dbo.associations.employee_lid > dbo.xdatagroupda72b87b.lid
Ref: dbo.associations.association_fklid > dbo.association_names.lid
Ref: dbo.surveys_tracking.connected_day > dbo.xdatagroupd8b41609.lid
Ref: dbo.surveys_tracking.fklid > dbo.ki_surveys.lid
Ref: dbo.xdatagroup455ae863.fklid > dbo.xtable423058f8.lid
Ref: dbo.xdatagroup86fd9c45.fklid > dbo.casestudies_db.lid
Ref: dbo.co2_general_type_unity_map.unity_id > dbo.co2_unities.lid
Ref: dbo.co2_general_type_unity_map.general_type_id > dbo.co2_emission_general_types.lid
Ref: dbo.xdatagroup01c77d95.fklid > dbo.xtable423058f8.lid
Ref: dbo.xdatagroup01c77d95.ref_b0e40b92 > dbo.xdatagroup74a2b33e.lid
Ref: dbo.xdatagroupf957bc73.ref_planner_lid > dbo.xdatagroupd8b41609.lid
Ref: dbo.xdatagroupf957bc73.ref_6379178d > dbo.xdatagroup453e0d78.lid
Ref: dbo.xdatagroupf957bc73.ref_6704352a > dbo.xdatagroupdc03d9cd.lid
Ref: dbo.xdatagroupf957bc73.ref_tolls_expense > dbo.xdatagroupf957bc73.lid
Ref: dbo.helpdesk_sub_category.fklid > dbo.helpdesk_scopes.lid
Ref: dbo.xdatagroupd8b41609.ref_a8b1e944 > dbo.xdatagroup453e0d78.lid
Ref: dbo.new_kim_employees.fklid > dbo.xdatagroup74a2b33e.lid
Ref: dbo.xdatagroup1cbaedf3.ref_f1ba868c > dbo.xtable423058f8.lid
Ref: dbo.xdatagroup1cbaedf3.ref_3315e1c6 > dbo.xdatagroup453e0d78.lid
Ref: dbo.invoice_payments.fklid > dbo.xdatagroup453e0d78.lid
Ref: dbo.expenses_reject_reasons_rel.standard_lid > dbo.expenses_reject_reasons_standard.lid
Ref: dbo.expenses_reject_reasons_rel.specific_lid > dbo.expenses_reject_reasons_specific.lid
Ref: dbo.projects_workshops.ref_ceb9881a > dbo.kaizen_event_workshops.lid
Ref: dbo.xdatagroup353ea8c1.l_id > dbo.ki_employee_team.lid
Ref: dbo.xdatagroup353ea8c1.fklid > dbo.xdatagroupda72b87b.lid
Ref: dbo.rates_matrix.ref_8961cb0a > dbo.parent_rate_matrix.lid
Ref: dbo.rates_matrix.ref_9dd190f6 > dbo.xdatagroup74a2b33e.lid
Ref: dbo.projects_country_deliver_days.fklid > dbo.xtable423058f8.lid
Ref: dbo.travelperkcostcenter.fklid > dbo.xtable423058f8.lid
Ref: dbo.xtable423058f8.ref_071edd0d > dbo.xdatagroup3cf9152f.lid
Ref: dbo.xtable423058f8.ref_15cf77be > dbo.xdatagroup74a2b33e.lid
Ref: dbo.xtable423058f8.ref_invoiced_by > dbo.xtable423058f8.lid
Ref: dbo.xtable423058f8.ref_startingpointlid > dbo.bu_rsu_starting_points.lid
Ref: dbo.xdatagroup453e0d78.l_resumebyaccount > dbo.xdatagroup6bfb60a3.lid
Ref: dbo.xdatagroup453e0d78.ref_f57e8322 > dbo.xdatagroupb42ad6bd.lid
Ref: dbo.xdatagroup453e0d78.ref_05e7a867 > dbo.xdatagroup74a2b33e.lid
Ref: dbo.xdatagroup453e0d78.ref_2495e2e9 > dbo.xtable423058f8.lid
Ref: dbo.xdatagroupde529862.fklid > dbo.casestudies_db.lid
Ref: dbo.xdatagroupf3be2299.fklid > dbo.xdatagroup453e0d78.lid
Ref: dbo.xdatagroupf3be2299.ref_813981e4 > dbo.xdatagroup6bfb60a3.lid
Ref: dbo.co2_po_invoices_metadata.ref_co2_single_emission > dbo.co2_single_emissions.lid
Ref: dbo.co2_po_invoices_metadata.fklid > dbo.po_invoices.lid
Ref: dbo.xdatagroup6b5f2644.fklid > dbo.xdatagroup06b81eb6.lid
Ref: dbo.co2_reason_general_map.reason_id > dbo.co2_emission_reasons.lid
Ref: dbo.co2_reason_general_map.general_id > dbo.co2_emission_general_types.lid
Ref: dbo.xdatagroup44427259.fklid > dbo.carerepdata.lid
Ref: dbo.co2_single_emissions.ref_expense > dbo.xdatagroupf957bc73.lid
Ref: dbo.co2_single_emissions.str_country > dbo.co2_emissions_factors_per_country.str_country
Ref: dbo.cvs_personal_data.lid > dbo.cvs_languages.fklid
Ref: dbo.invoices_connections.l_original > dbo.xdatagroup453e0d78.lid
Ref: dbo.validated_routes.postal_code > dbo.routes_distances.str_starting_zip